/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200QuotasPerProject', 'model/InlineResponse200QuotasProjects'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse200QuotasPerProject'), require('./InlineResponse200QuotasProjects'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.AccountQuotaModel = factory(root.TrainingApi.ApiClient, root.TrainingApi.InlineResponse200QuotasPerProject, root.TrainingApi.InlineResponse200QuotasProjects);
  }
}(this, function(ApiClient, InlineResponse200QuotasPerProject, InlineResponse200QuotasProjects) {
  'use strict';




  /**
   * The AccountQuotaModel model module.
   * @module model/AccountQuotaModel
   * @version 1.0
   */

  /**
   * Constructs a new <code>AccountQuotaModel</code>.
   * Represents a set of quotas assocated with an account
   * @alias module:model/AccountQuotaModel
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>AccountQuotaModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountQuotaModel} obj Optional instance to populate.
   * @return {module:model/AccountQuotaModel} The populated <code>AccountQuotaModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Tier')) {
        obj['Tier'] = ApiClient.convertToType(data['Tier'], 'String');
      }
      if (data.hasOwnProperty('Projects')) {
        obj['Projects'] = InlineResponse200QuotasProjects.constructFromObject(data['Projects']);
      }
      if (data.hasOwnProperty('Predictions')) {
        obj['Predictions'] = InlineResponse200QuotasProjects.constructFromObject(data['Predictions']);
      }
      if (data.hasOwnProperty('PerProject')) {
        obj['PerProject'] = ApiClient.convertToType(data['PerProject'], [InlineResponse200QuotasPerProject]);
      }
    }
    return obj;
  }

  /**
   * Gets the tier of user
   * @member {String} Tier
   */
  exports.prototype['Tier'] = undefined;
  /**
   * @member {module:model/InlineResponse200QuotasProjects} Projects
   */
  exports.prototype['Projects'] = undefined;
  /**
   * @member {module:model/InlineResponse200QuotasProjects} Predictions
   */
  exports.prototype['Predictions'] = undefined;
  /**
   * Gets a list of quotas that apply per-project for each project
   * @member {Array.<module:model/InlineResponse200QuotasPerProject>} PerProject
   */
  exports.prototype['PerProject'] = undefined;



  return exports;
}));


