/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.InlineResponse200QuotasProjects = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse200QuotasProjects model module.
   * @module model/InlineResponse200QuotasProjects
   * @version 1.0
   */

  /**
   * Constructs a new <code>InlineResponse200QuotasProjects</code>.
   * Represents a quota
   * @alias module:model/InlineResponse200QuotasProjects
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse200QuotasProjects</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200QuotasProjects} obj Optional instance to populate.
   * @return {module:model/InlineResponse200QuotasProjects} The populated <code>InlineResponse200QuotasProjects</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Total')) {
        obj['Total'] = ApiClient.convertToType(data['Total'], 'Number');
      }
      if (data.hasOwnProperty('Used')) {
        obj['Used'] = ApiClient.convertToType(data['Used'], 'Number');
      }
      if (data.hasOwnProperty('TimeUntilReset')) {
        obj['TimeUntilReset'] = ApiClient.convertToType(data['TimeUntilReset'], 'String');
      }
    }
    return obj;
  }

  /**
   * The total allowable amount in the quota
   * @member {Number} Total
   */
  exports.prototype['Total'] = undefined;
  /**
   * The amount of quota that has currently been used
   * @member {Number} Used
   */
  exports.prototype['Used'] = undefined;
  /**
   * Gets the time remaining until the quota resets. Null if this quota does not reset.
   * @member {String} TimeUntilReset
   */
  exports.prototype['TimeUntilReset'] = undefined;



  return exports;
}));


