/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse200Keys', 'model/InlineResponse200Quotas'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse200Keys'), require('./InlineResponse200Quotas'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.InlineResponse200 = factory(root.TrainingApi.ApiClient, root.TrainingApi.InlineResponse200Keys, root.TrainingApi.InlineResponse200Quotas);
  }
}(this, function(ApiClient, InlineResponse200Keys, InlineResponse200Quotas) {
  'use strict';




  /**
   * The InlineResponse200 model module.
   * @module model/InlineResponse200
   * @version 1.0
   */

  /**
   * Constructs a new <code>InlineResponse200</code>.
   * Represents a user account
   * @alias module:model/InlineResponse200
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200} obj Optional instance to populate.
   * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('UserName')) {
        obj['UserName'] = ApiClient.convertToType(data['UserName'], 'String');
      }
      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('Keys')) {
        obj['Keys'] = InlineResponse200Keys.constructFromObject(data['Keys']);
      }
      if (data.hasOwnProperty('Quotas')) {
        obj['Quotas'] = InlineResponse200Quotas.constructFromObject(data['Quotas']);
      }
    }
    return obj;
  }

  /**
   * Gets the name of the account owner
   * @member {String} UserName
   */
  exports.prototype['UserName'] = undefined;
  /**
   * Gets the email associated with this account
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;
  /**
   * @member {module:model/InlineResponse200Keys} Keys
   */
  exports.prototype['Keys'] = undefined;
  /**
   * @member {module:model/InlineResponse200Quotas} Quotas
   */
  exports.prototype['Quotas'] = undefined;



  return exports;
}));


