/**
 * TrainingApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TrainingApi) {
      root.TrainingApi = {};
    }
    root.TrainingApi.ProjectsSettings = factory(root.TrainingApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProjectsSettings model module.
   * @module model/ProjectsSettings
   * @version 1.0
   */

  /**
   * Constructs a new <code>ProjectsSettings</code>.
   * Represents settings associated with a project
   * @alias module:model/ProjectsSettings
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ProjectsSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectsSettings} obj Optional instance to populate.
   * @return {module:model/ProjectsSettings} The populated <code>ProjectsSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('DomainId')) {
        obj['DomainId'] = ApiClient.convertToType(data['DomainId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the id of the Domain to use with this project
   * @member {String} DomainId
   */
  exports.prototype['DomainId'] = undefined;



  return exports;
}));


